service: auction-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
